"""empty message

Revision ID: 3db95522f0f0
Revises: 
Create Date: 2019-09-14 15:14:18.504700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db95522f0f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserData')
    # ### end Alembic commands ###
